[mailToSlack]
    [mailToSlack.in]
        [mailToSlack.in.mail]
            server = "imap@mail.com:993"
            user = "user@xxx.xxx"
            password = "xxxx"
        [mailToSlack.in.policy]
            count = 10
            intervalSeconds = 100
        [mailToSlack.in.filter]
            subject = "subjects"
            from = "@system.info"
            body = "need to notification"
    [mailToSlack.out]
        [mailToSlack.out.http]
		    method = "GET"
		    url = "https://slack.com/api/chat.postMessage?aaa=bb"
        [mailToSlack.out.policy]
	    	count = 10
	    	intervalSeconds = 100
